[project]
name = "llnca"
version = "0.2.0"
description = "large language neural cellular automata"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "torch>=2.13.0",
    "tqdm>=4.69.1",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
